### ISSUE TITLE
ipad Safari: MANUFACTURERS SLIDE

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#1]
Text is still being cut off and appearing behind the image. Whereas the image itself is not bleeding all the way to the right. See screenshot.
![8bf6b7819a8593918bf15d9947fa02241597fb5eb07248be2e pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/20408671/21110446/11e0c264-c052-11e6-9a4b-4827009449d9.jpg)

**Comment by CALLVES** [comment]
Just want you to know that this is still an issue.... thanks.

**Comment by juliafrichbeet** [comment]
Fixed for Ipad, I deleted image for lanscape mode - that is something with flex properties becauce of mark up we use here. tODAY i WILL CONTINUE FIXING iPHONE BUGS

**Comment by CALLVES** [comment]
Thanks

**Comment by CALLVES** [comment]
My one concern with this Julia, please see this screenshot, this is on my PC Chrome desktop view, now all text is crunched to the left.
![screenshot 2016-12-16 11 26 52](https://cloud.githubusercontent.com/assets/20408671/21275633/9efca31a-c382-11e6-8a86-bffbfe7a1f64.jpg)
