### ISSUE TITLE
Set Font Styling for H1 and H2 have disappeared

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#10]
Julia, please check again what we were setting up for H1 and H2 styling all across the home page slides and interior pages have disappeared.

**Comment by CALLVES** [comment]
Just checked again, specifically STAY CONNECTED slide heading, it's showing at 70px and this should be the H1, lato-light 40px / 44px.  And SERVICES slide, THREE GOOD REASONS heading, is now 50px instead of the H1, lato-light 40 px / 44 px.

**Comment by juliafrichbeet** [comment]
Changed, please check
