### ISSUE TITLE
SEARCH results - products

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#12]
When a user searches for a specific product for example "CHAIRS" from the home page search tool. And they get a result that is an actual product.. Is it possible to make the link just connect directly to whatever the external URL is? Right now, when you click on a result from the results page, after searching "CHAIRS" it takes you to a product details page. And this is not what the client wants.
![a5cb9613aa1b214f1d3d55b6dda5e0fe6e33b35269bca36826 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/20408671/21131455/a0c7626e-c0c3-11e6-96f8-e9f4acb4b5db.png)

**Comment by juliafrichbeet** [comment]
Added back end to search template. Now if there is a product in a search result - link goes to external URL
