### ISSUE TITLE
PC Chrome: NEWS feed on home page has a weird gap

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#15]
![screenshot 2016-12-14 11 13 15](https://cloud.githubusercontent.com/assets/20408671/21196934/7338bf24-c1ee-11e6-9472-8e7eeb6e845a.jpg)

**Comment by CALLVES** [comment]
I see that the red background is gone but now the NEWS feed bar is high up. See screenshot attached.
![screenshot 2016-12-14 15 54 06](https://cloud.githubusercontent.com/assets/20408671/21206315/04414faa-c216-11e6-9e17-f1a342fe3b63.jpg)

**Comment by juliafrichbeet** [comment]
Fixed, please chek
