### ISSUE TITLE
#001000: Home page icons

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#17]
All icons should have a different color for the roll-over state. Instead of white it should be a lighter grey color, please see the PSD file for exact HEX#: https://www.dropbox.com/s/0n4ozaa031k4asg/M3_HomepageDesign_Final.psd?dl=0

**Comment by juliafrichbeet** [comment]
I took #DEDCDE; from psd - added to icons on hover state

**Comment by CALLVES** [comment]
Hi Julia, sorry this one is not closed yet. So there is a color change on the icon background as well. See this PSD: https://www.dropbox.com/s/qwf60ot3mx1o2rx/M3_HomepageDesign_Final.jpg?dl=0

**Comment by juliafrichbeet** [comment]
Sorry,I took colors from this JPG,seems like they dont match exactly . It would be great if you could provide me with psd. Thank you!

**Comment by juliafrichbeet** [comment]
Please check colors I used on dev now, also I think I should add styles for menu item when each slide is active/opened

**Comment by CALLVES** [comment]
OK, I think on dev it looks fine. I just noticed the keyline under the M3 logo in the black right hand nav bar seems to be too high up. When you hover over the hamburger menu do you see how the color box is not filling up? But then the keyline is floating above? Maybe move that keyline down to match the colored box?

**Comment by juliafrichbeet** [comment]
I fixed margins but unfortunately we can not add hover effect on logo - logo image takes all the place in that icon,

**Comment by CALLVES** [comment]
That's ok, this looks good. You can go ahead and deploy this to the live site.
