### ISSUE TITLE
#001049: SEARCH RESULTS page

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#18]
"Please clean this page up. Everything should have a heirarchy. Headline, subhead and body copy. See notes here ...

https://www.dropbox.com/s/www0t35s19q4qge/search-landing-page-notes.jpg?dl=0
"

Pleas make sure all product details pages are disabled!

**Comment by juliafrichbeet** [comment]
Could you please check search results page now? I added new styles. for new heading and some content shown, links to products lead to external resourses now. Please let me know if I should add anything else

**Comment by CALLVES** [comment]
This is looking good but I still see the weird symbols:
![screenshot 2016-12-15 10 15 01](https://cloud.githubusercontent.com/assets/20408671/21236305/5b1820f8-c2af-11e6-96a7-a2e63aeeeb1b.jpg)

**Comment by juliafrichbeet** [comment]
I'll clean DB tomorrow so it wont appear

**Comment by CALLVES** [comment]
OK thanks let me know when you're done with that.

**Comment by CALLVES** [comment]
How is this task going? I see that the weird symbols are still an issue. On both live and dev sites.

**Comment by juliafrichbeet** [comment]
Please check now!
