### ISSUE TITLE
#001020 HOME page Products Slide

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#19]
Home Products - We need a smaller space between paragraphs on the left and right. The margins on both sides should match, as well. The margin on the right is too big. All margins from page to page should match. The top margin should also match all other pages. Right now it is VERY big and pushes all copy down. The About Us page is a good margin example to follow. 

Client note: "This is not done. I still see different 
margins on the right and the left and the copy on left should be align-left. 
Please see notes given to Val on Dec. 10"

**Comment by juliafrichbeet** [comment]
Latest styles have been missinng, uploaded and added new. Please check

**Comment by CALLVES** [comment]
Thanks. So I don't think that this is a big deal, but I can tell the client is very measuring about the margins. Please see my screenshot. I want to hear your thoughts because I don't want us to waste time on something we can't really control.
![screenshot 2016-12-15 10 09 25](https://cloud.githubusercontent.com/assets/20408671/21236150/b8b61630-c2ae-11e6-8348-90d9c0f94443.jpg)

**Comment by juliafrichbeet** [comment]
Sure, I understand - please check this screenshot 
![image](https://cloud.githubusercontent.com/assets/24528105/21240894/f2076148-c315-11e6-9ac9-9d16e90422be.png)

**Comment by CALLVES** [comment]
OK Im good with this and Ill explain to them about this if they still complain. Thank you.

**Comment by CALLVES** [comment]
Hi Julia, so the other issue too is the paragraph breaks are not consistent again. Please see this screenshot.
![screenshot 2016-12-16 11 35 48](https://cloud.githubusercontent.com/assets/20408671/21275997/4efdaa88-c384-11e6-8028-fcb1a3ff9ed4.jpg)

**Comment by juliafrichbeet** [comment]
Added both for dev and live.please check

**Comment by CALLVES** [comment]
The dev version looks good, the live version doesn't look the same. Also I see the weird symbol is back on the live and dev site.  You can see on Chrome on the PRODUCTS slide and also other slides and pages. Please check through the whole site.

**Comment by juliafrichbeet** [comment]
I just didn't implementaed latest styles fixes on live without your confirmation, I can do that easily! Sorry, can please check symbols again? Because I was working with that yesterday!
