### ISSUE TITLE
ipad Safari: SERVICES slide

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#2]
The right column is not stretching all the way down, ends half way down whereas the left column stretches. But I think this shouldn't even have to scroll? Can't they just resize to fit in 1 window?
![2016-12-12](https://cloud.githubusercontent.com/assets/20408671/21110555/7d93cdda-c052-11e6-8991-a52463b07b12.jpg)

**Comment by juliafrichbeet** [comment]
Fixed, pleasee check
