### ISSUE TITLE
#001051 Overall testing of online forms and online submissions

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#20]
"I tested the CONNECT form on the homepage, entered an email address but it doesn't do anything. This should tie into their MailChimp account. And after a user submits their email address they should get a THANK YOU page, please use this design: https://www.dropbox.com/s/e17byp2q99qb20r/M3_Thank%20you.psd?dl=0  

Additionally after I submitted on the CONTACT page form, I should get an email confirmation with a Summary of the online form submission. So far I have not seen anything. Though in the WP admin I do see that it goes to patti@m3office.com"

"Client's MailChimp account: 
u: valerie@olivespark.com
p: Val@O+S2016"	Julia please use this API key: b9d7268220880ad0c2088a43def13223-us14

**Comment by juliafrichbeet** [comment]
Thank you page template is ready, please check. Need to work with mailchimo settings - does not redirect now
http://www.m3office.com/thank-you/

**Comment by CALLVES** [comment]
Hi Julia, OK so far the STAY CONNECTED page submission works PERFECT! I got my confirmation emails.

 
![thank you confirmation email mailchimp 2](https://cloud.githubusercontent.com/assets/20408671/21235801/2dde1612-c2ad-11e6-87a3-068025c92c75.png)
![thank you confirmation email mailchimp](https://cloud.githubusercontent.com/assets/20408671/21235802/2de3e312-c2ad-11e6-90cd-eb0f5afdcf69.jpg)

However, the CONTACT page form submission doesn't seem to send me a confirmation email yet. Is this something that is set-up via MailChimp? I think it doesn't need to be through MailChimp, since the submission goes straight to their email. But would be good to get a THANK YOU notice for submitting online.

**Comment by juliafrichbeet** [comment]
Is this a new template for thank you page? Still can not figure out why it not redirecting me there after submit..

**Comment by CALLVES** [comment]
So the 2 screenshots I showed you is what I get in my email. But there should be a thank you page that appears when I submit my email on the STAY CONNECTED page. This is the THANK YOU page, I think this is good for now.
![screenshot 2016-12-16 11 29 19](https://cloud.githubusercontent.com/assets/20408671/21275697/f12e6826-c382-11e6-8a11-f9e180728c06.jpg)

**Comment by juliafrichbeet** [comment]
Please check on live - it takes user to thank you page after you submit the sign up form on the main page
