### ISSUE TITLE
CONTACT page margins

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#21]
The gap between the 2 columns are now very close again, could you widen the gap?

**Comment by juliafrichbeet** [comment]
Reduced, please confirm

**Comment by CALLVES** [comment]
Actually the real issue is that the right hand margins seem so empty because there is not much going on with the right column content.

Use this embed code instead, will give you a MEDIUM size map:
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3303.3367370997726!2d-118.1739828486406!3d34.11212802192291!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c46f450fbddb%3A0x7df17a62b6c2e67a!2s161+Pasadena+Ave+a%2C+South+Pasadena%2C+CA+91030!5e0!3m2!1sen!2sus!4v1481823711541" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

**Comment by CALLVES** [comment]
![screenshot 2016-12-15 09 40 44](https://cloud.githubusercontent.com/assets/20408671/21236188/de804dea-c2ae-11e6-9032-2f50d731418d.jpg)

**Comment by juliafrichbeet** [comment]
Please check layout now

**Comment by CALLVES** [comment]
Much better! Thank you.
