### ISSUE TITLE
ipad Safari: behavior of clicking into internal pages from home page

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#24]
I'm testing this on an ipad, using Safari. Every time I click on the items from the hamburger menu to go itno the internal pages it goes to the page but the right side hamburger menu is CLOSED. See screenshots.
![ipad safari_services page](https://cloud.githubusercontent.com/assets/20408671/21236850/7165ee10-c2b1-11e6-9e8c-7d9589501c89.jpg)
![ipad safari_about us page](https://cloud.githubusercontent.com/assets/20408671/21236849/7165acc0-c2b1-11e6-85cd-251caced9736.png)

**Comment by juliafrichbeet** [comment]
Please try now. Semms like it's open. I see some code which uses local storage - it cloded menu if it was closed on previous page

**Comment by CALLVES** [comment]
Hi Julia, I tested on ipad and it's still staying closed as a hamburger menu whenever I click into the internal pages.

What do you think is the issue?

Also do you see how that photo is not going all the way down? It's cutoff... Let me know...

**Comment by juliafrichbeet** [comment]
To be honest, I can not get reproduce that. But I removed that code with local storage. Please try to clear cahce and try agan. 
Do you mean that image on the right column on about page is not 100% height?

**Comment by juliafrichbeet** [comment]
Please check about page layout

**Comment by CALLVES** [comment]
OK, the ABOUT page on ipad looks much better. Thanks!

What about the menu on the right not sticking and staying open? It keeps closing each time I click to another page.

**Comment by CALLVES** [comment]
Hi Julia, do you have any updates on this item?
