### ISSUE TITLE
PRIVACY POLICY page

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#25]
This is just a question, wondering if it's a lot of work to tweak the layout, to make the text wrap around the image instead? So the right hand side is not so empty?

See my screenshot:
![screenshot 2016-12-15 10 13 32](https://cloud.githubusercontent.com/assets/20408671/21237280/20a1c524-c2b3-11e6-8ae3-4b73c21b2910.jpg)

**Comment by juliafrichbeet** [comment]
Please check now when I changed layout - it's like on mobile and the image is always at the bottom

**Comment by CALLVES** [comment]
This looks beautiful, Thanks for taking care of this!
