### ISSUE TITLE
ipad all browsers: PRODUCTS page broken layout

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#26]
On all browsers on ipad I noticed that the PRODUCTS page layout is broken. Please see screenshot.
![ipad safari_products](https://cloud.githubusercontent.com/assets/20408671/21237602/7f63b1c0-c2b4-11e6-8e95-a97fac2cbab1.jpg)

**Comment by juliafrichbeet** [comment]
Added 3 products per line for horizontal layout, please check

**Comment by CALLVES** [comment]
Looks fixed, but see the PRODUCT SEARCH field is slightly lower than the CATEGORIES and SOLUTIONS dropdowns... please see screenshot
![ipad safari_products page_2](https://cloud.githubusercontent.com/assets/20408671/21246504/119cae7e-c2de-11e6-81e8-0ae085f7a5ad.png)

**Comment by juliafrichbeet** [comment]
Thare was a difference in 4 px, thank you, fixed
