### ISSUE TITLE
ipad all browsers: CONTACT page

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#27]
This layout is also broken, the M3 map and contact info is pushed down, should be in the right column for balance. See screenshot:
![ipad_contact](https://cloud.githubusercontent.com/assets/20408671/21237686/e520561c-c2b4-11e6-8e37-c37010ebe5b1.png)

**Comment by juliafrichbeet** [comment]
Fixed, please confirm

**Comment by CALLVES** [comment]
This works. Thank you!
