### ISSUE TITLE
ipad all browsers: PRIVACY POLICY page

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#28]
On this page, when I open in ipad all browsers, the image is taking over the whole page, can you change so the text appears first before image? Or the image is made smaller and the text wraps around so you can see immediately? Right now all I see is an image and that's it. Doesn't make sense to the typical user.
![ipad_privacy_policy](https://cloud.githubusercontent.com/assets/20408671/21237798/512a778e-c2b5-11e6-8a4c-85286a1651cd.jpg)

**Comment by juliafrichbeet** [comment]
Please check layout, I changed that

**Comment by CALLVES** [comment]
This is great. Thanks!
