### ISSUE TITLE
iphone only mobile responsive issues

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#29]
Please see these screenshots, you'll see that the MANUFACTURERS slide is cutoff, the text runs behind the image, etc. Maybe on mobile just remove the image completely.

And see the other pages, you'll notice that they are not responding correctly to being mobile.

On my SAMSUNG phone it is fine.
![img-20161215-wa0010](https://cloud.githubusercontent.com/assets/20408671/21246359/0ee339b0-c2dd-11e6-8288-81660b7d3a94.jpg)
![img-20161215-wa0007](https://cloud.githubusercontent.com/assets/20408671/21246358/0edf977e-c2dd-11e6-9322-43dc367c4fb2.jpg)
![img-20161215-wa0008](https://cloud.githubusercontent.com/assets/20408671/21246360/0eed1372-c2dd-11e6-85f9-16bbeed0e88b.jpg)
![img-20161215-wa0009](https://cloud.githubusercontent.com/assets/20408671/21246361/0f16214a-c2dd-11e6-835f-24157d6ecfc4.jpg)

**Comment by CALLVES** [comment]
One more screenshot from client's iphone, this is the MANUFACTURERS slide on her phone.
![img_3162](https://cloud.githubusercontent.com/assets/20408671/21250096/6d8d518e-c2f7-11e6-9762-2acc937e168c.PNG)

**Comment by juliafrichbeet** [comment]
Tested all the slides on Iphone 6, please check dev version

**Comment by CALLVES** [comment]
Julia is this issue resolved only on the dev version?

**Comment by juliafrichbeet** [comment]
I moved to live alll the styles from that time. I'll check live tomorrow again on MAc/iphone/Ipad anyway

**Comment by CALLVES** [comment]
OK thanks.

**Comment by juliafrichbeet** [comment]
Checked on iphone/iPAD AND ie
