### ISSUE TITLE
iphone off-centered pages

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#30]
Attached are screen captures and notes below:

On Chrome:
- Most of the mobile site is slightly off-center (see screen captures)
- Vendors list runs under image at bottom
- Page margins on Home Services page are really big, Our Services is off centered and the bottom image is really small
- Stay Connected page, all is slightly off-center and the social icons are a little too big

On Safari:
- Most of the mobile site is slightly off-center (see screen captures)
- Vendors list runs under image at bottom
- Page margins on Home Services page are really big, Our Services is off centered and the bottom image is really small
- Stay Connected page, all is slightly off-center and the social icons are a little too big
![img_3165](https://cloud.githubusercontent.com/assets/20408671/21250547/fa7048b0-c2fa-11e6-9874-ae00baccc12a.PNG)
![img_3166](https://cloud.githubusercontent.com/assets/20408671/21250548/fa734b46-c2fa-11e6-8906-ed5888d07398.PNG)
![img_3162](https://cloud.githubusercontent.com/assets/20408671/21250549/fa742cdc-c2fa-11e6-96b0-f9b308c34f54.PNG)
![img_3163](https://cloud.githubusercontent.com/assets/20408671/21250550/fa798448-c2fa-11e6-938a-b5d1f5569e83.PNG)

**Comment by juliafrichbeet** [comment]
added fixes on dev, please check
