### ISSUE TITLE
desktop view: STAY CONNECTED slide edits

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#31]
Julia, the client wants us to still make updates to this page. Please see screenshot:
![1948faa366bea3c57ab7af7b67111f803a0dcd33fe99600db4 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/20408671/21276091/bff01b2c-c384-11e6-90ec-5e3684a57c57.jpg)

**Comment by juliafrichbeet** [comment]
Implemented on dev, please confirm

**Comment by CALLVES** [comment]
Hi Julia, sorry I was at a conference, so I checked and this is what I see where everything is squished... 
![screenshot 2016-12-20 12 38 28](https://cloud.githubusercontent.com/assets/20408671/21367121/b5fb0f3e-c6b1-11e6-9004-e14098336ea4.jpg)

**Comment by juliafrichbeet** [comment]
I have seen previous screenshot and I thought I shoud reduce input and text below. Please let m eknow if I was wrong! Sorry for misunderstanding

**Comment by CALLVES** [comment]
Hi Julia,

In the previous screenshot that the client provided, the gap that she wanted to reduce is between the social media icons only. Also, the request to reduce the size of the SUBSCRIBE field box is just for the box and not to reduce the text.

Please fix everything back to the way it was. And please follow the instructions very carefully. The client is very particular about these types of details.

Thank you.

**Comment by CALLVES** [comment]
Disregard what I said about the text below the form field... client said just leave it as is in terms of making it the same width as the form field...
