### ISSUE TITLE
Client's PC frontend issues

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#32]
Julia, can you take a look at the attached PDF from client? She is seeing this on her end and she is using a PC. This is the LIVE site that she is reviewing.

Her notes: Here are screens shots of 2 issues I found.  The “manufacturer” page and also on the “Specials” tab it the verbiage has some added characters after the word “today”.  I hope that doesn’t mean we have been hacked already.  I haven’t looked at the other pages.  I use internet explorer.

[M3 scrren shots.pdf](https://github.com/CALLVES/M3office/files/664741/M3.scrren.shots.pdf)

**Comment by juliafrichbeet** [comment]
All the issues on live will be gone after I will deploy latest fixes from dev!

**Comment by CALLVES** [comment]
OK. So you've seen the above issues? Just making sure that you are responding directly to individual issues...

**Comment by juliafrichbeet** [comment]
Sure. I see, I added few more queries to delete those symbols. But on PC manufacturer slide is OK, anyway, need to upload latest styles

**Comment by CALLVES** [comment]
OK but the issues they are showing such as the SPECIALS icon mouse over, there is still no text that shows up. Can you please make sure that this is fixed ASAP?
