### ISSUE TITLE
ABOUT page margins

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#33]
Julia, can you see this email from client?

About Page margins on the left and right on the copy side don't seem to match and is pushing the copy to the left. Can Julia check to make sure both margins match?

**Comment by juliafrichbeet** [comment]
I fixed about page margins - I suppose some inconsistensies on live. Unfortunately, I can test on Mac desktop only tomorrow - not available now.

**Comment by CALLVES** [comment]
OK please test on Mac first then let me know.... before I close this bug
