### ISSUE TITLE
Safari on Mac laptop issues

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#34]
Hi Julia, can you see the attachments from the client below?
[additionalm3issuesbugsonsafari9_1_2onmaclaptop.zip](https://github.com/CALLVES/M3office/files/668020/additionalm3issuesbugsonsafari9_1_2onmaclaptop.zip)

**Comment by juliafrichbeet** [comment]
Unfortunately, I can test on Mac desktop only tomorrow - not available now. I will provide you with update tomorrow morning. Sorry for inconveniences!

**Comment by CALLVES** [comment]
OK once you are able to test on Mac please let me know ASAP before I close this bug.

**Comment by CALLVES** [comment]
Hi Julia, what is the status of this bug that was reported by the client?

**Comment by juliafrichbeet** [comment]
Yes, only manufactures slide left!  But culd you please specify issue regarding doggies page? W Please check the screenshot - http://prntscr.com/dnhcap

**Comment by CALLVES** [comment]
I can't see it on mac safari I don't have a mac, but it looks like the client initially saw that the text is way too small, then I think we increased the size but then it caused issues on the smaller screen where you saw the text was going over the lines, etc. Not sure really, let me double check with them.

**Comment by CALLVES** [comment]
I found this note from the client, just double check against it:

Times New Roman is still showing up on mobile (Safari & Chrome on Iphone 6S) and Firefox desktop

**Comment by juliafrichbeet** [comment]
Added on live, but I still cant see if there any times new roman... sometimes browsers need time to render fonts, it's about second (e.g. IE) Please let me know on what pages that happens, if possible.

**Comment by CALLVES** [comment]
I'm awaiting the client’s confirmation on this

**Comment by juliafrichbeet** [comment]
Got it!

**Comment by CALLVES** [comment]
OK so on the DOGGIES view thing, basically she said the URL on DOGGIES page needs to be the same size as the rest of the text above it. She's asking why it's so small? Is this because you had to decrease it so on small screens it doesn't break through the container?

**Comment by juliafrichbeet** [comment]
It just was like this from the very beginning! I made the same size as text above, just reduces that a little bit on mobile

**Comment by CALLVES** [comment]
OK thanks Julia. I think we're good here.
