### ISSUE TITLE
Random Symbols in NEWS page

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#36]
Hi Julia, I don't know if this is an older issue that was already there before you fix it.
But if you go to this page: http://www.m3office.com/news/page/55/
or look at the screenshot you can see the weird 
![screenshot-www m3office com 2016-12-21 22-35-02](https://cloud.githubusercontent.com/assets/20408671/21417220/db5724a8-c7cd-11e6-8107-20eae2c8af99.png)
symbols are there.

**Comment by juliafrichbeet** [comment]
These synbols removed from DB, plase check!
