### ISSUE TITLE
HOME - Specials ICON mouse over

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#38]
Hi Julia,

There is supposed to be text that says SPECIALS when you mouse over the icon just like all the other icons on the home page.

SPECIALS is missing this text, can you please fix this ASAP?

**Comment by juliafrichbeet** [comment]
No problem, I see that, too

**Comment by juliafrichbeet** [comment]
Added, please check

**Comment by CALLVES** [comment]
This is good. I'm going to close out.
