### ISSUE TITLE
PC IE - MANUFACTURERS slide

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#39]
Hi Julia, this is a really bad and URGENT issue that the client is now upset about. See screenshot, this is how the MANUFACTURERS slide appears on their end. I tested on my PC IE as well, it shows up this way as well.
![screenshot 2016-12-22 13 00 59](https://cloud.githubusercontent.com/assets/20408671/21440221/c7c27fcc-c846-11e6-8b04-e1faebd9350d.jpg)

**Comment by juliafrichbeet** [comment]
I can't see that on chrome, but see in IE. I'm sure that happend because of flex property we use. Some browsers still dont support that. But t was the only way to implement logic like this - giv you a possibility to add column in backoffice// I'll see what I can do ASAP!

**Comment by CALLVES** [comment]
Hi Julia,

The client sent me this note to see if it would help us: I reached out to my developer friend about the IE issue and here is what he said ...


From what I can tell I think the issue might be the support level for CSS3 multiple columns in the div. I don’t think IE supports this until IE 10, and anything before that requires some jQuery to compensate for this.
Line 640 in the latest-fixes.css file uses a bunch of CSS3, so the way this is setup might have to be tweaked, or there are workarounds but they’d have to be researched and applied… For example here’s one that works with javascript:
http://jsfiddle.net/HP85j/393/

Take a look and let me know what you think.

**Comment by CALLVES** [comment]
OK the MANUFACTURERS slide looks good on the DEV site, please go ahead and deploy this to the live server. BUT be careful on the dev server I still see those weird symbols so don't bring that over to the live site. Thanks Julia!

**Comment by juliafrichbeet** [comment]
Sure! I will add only new styles and template! Thnak you

**Comment by CALLVES** [comment]
Thanks Julia. Let me know when this is up. The client is waiting on this one piece for the IE on PC issue.

**Comment by juliafrichbeet** [comment]
Added on live!
