### ISSUE TITLE
ipad Safari: SPECIALS slide

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#4]
The 2 columns are not working, the right image is cutoff and only showing a small portion. The page should be centered and showing 2 columns equally just the way it appears on the desktop.
![2016-12-12](https://cloud.githubusercontent.com/assets/20408671/21110775/7a1539fe-c053-11e6-88aa-d0d544a3451c.png)

**Comment by juliafrichbeet** [comment]
Fixed, please confirm
