### ISSUE TITLE
WP Admin: Install WP security plugins to avoid any attack on the online forms

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#41]
My recommendations: WPBruiser to protect the online forms, UpdraftPlus for WP backup and Wordfence for overall security bots and other IP attacks. Please feel free to suggest your own plugins for these purposes.

Julia once you install WPBruiser and Wordfence I believe you have to add your IP address to the WHITELIST so you're not locked out.

**Comment by juliafrichbeet** [comment]
I installed two plugins WPBruiser and Wordfence . I didnt works with them before, so I have to read more about it
For backups we already have duplicator plugon on site (which makes copy of WP and DB) and also DB migrate (for DB only)

**Comment by CALLVES** [comment]
Ok. Nw, for wordfence you need to add your IP Address to the white list. Otherwise you won't be able to login to the WP admin anymore. Please use this email address for any settings: valerie@olivespark.com

**Comment by juliafrichbeet** [comment]
Ok, thank you, I'll do it now
