### ISSUE TITLE
Pass through Google Mobile-Friendly

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#42]
https://search.google.com/search-console/mobile-friendly?url=http%3A%2F%2Fwww.m3office.com%2F

I tried to test on Google Mobile-Friendly and I got this error message:

We can’t access the page
This could be because the page is unavailable or blocked by robots.txt

We need to be careful about this because the site needs to be SEO friendly as well.

**Comment by juliafrichbeet** [comment]
I added robots.txt file, while there was a line - Disallow: / there, Google colud not test the site

![image](https://cloud.githubusercontent.com/assets/24528105/21471791/ba88395a-cac6-11e6-95da-da055deb4557.png)

**Comment by CALLVES** [comment]
Ok so when can we run this test?

**Comment by juliafrichbeet** [comment]
Sorry, what exactly test do you mean?  Im currently working with Google speed test result

**Comment by CALLVES** [comment]
Sorry I think I was responding to the wrong window :)

**Comment by juliafrichbeet** [comment]
Thats OK :)
