### ISSUE TITLE
Compressing files on their live server

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#44]
Once we are done they want us to help reduce the file sizes on their live server because now they are out of space.

**Comment by CALLVES** [comment]
Got this from the server support:

We don't have any sort of test that can determine which files are not needed. This would ultimately be left up to you or your developer to determine. I've provided a breakdown of your disk usage that includes large files and directories below for reference. I've increased your disk quota by 10G and have this set to re-open so we can change it back on Friday.

---------- Large Directories ---------------------------------------------------
121M    ./m3office.com/html.premove
15G     ./m3office.com/UpDraft_BackUp
8.4G    ./m3office.com/html/wp-content
13G     ./m3office.com/html/wp-snapshots
22G     ./m3office.com/html
37G     ./m3office.com
37G     .

---------- Large Files ---------------------------------------------------------
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 19 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads8.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads12.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 19 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads5.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads15.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 12 18:42 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 12 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads15.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads14.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 19 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads.zip
-rw-r--r-- 1 mthreeof mthreeof 397M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads12.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads9.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 19 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads7.zip
-rw-r--r-- 1 mthreeof mthreeof 397M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads17.zip
-rw-r--r-- 1 mthreeof mthreeof 397M Dec 12 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads14.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads13.zip
-rw-r--r-- 1 mthreeof mthreeof 400M Dec 19 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads6.zip
-rw-r--r-- 1 mthreeof mthreeof 395M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads7.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 12 18:42 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads2.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 19 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads4.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads18.zip
-rw-r--r-- 1 mthreeof mthreeof 400M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads6.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 12 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads17.zip
-rw-r--r-- 1 mthreeof mthreeof 400M Dec 19 18:46 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads20.zip
-rw-r--r-- 1 mthreeof mthreeof 396M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads13.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads10.zip
-rw-r--r-- 1 mthreeof mthreeof 400M Dec 12 18:42 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads3.zip
-rw-r--r-- 1 mthreeof mthreeof 400M Dec 12 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads16.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads11.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 19 18:46 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads19.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads8.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads16.zip
-rw-r--r-- 1 mthreeof mthreeof 398M Dec 19 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads2.zip
-rw-r--r-- 1 mthreeof mthreeof 400M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads5.zip
-rw-r--r-- 1 mthreeof mthreeof 395M Dec 19 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads3.zip
-rw-r--r-- 1 mthreeof mthreeof 400M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads10.zip
-rw-r--r-- 1 mthreeof mthreeof 396M Dec 19 18:45 ./m3office.com/UpDraft_BackUp/backup_2016-12-19-1537_M3_Office_c478c5643b60-uploads9.zip
-rw-r--r-- 1 mthreeof mthreeof 196M Dec 12 18:44 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads18.zip
-rw-r--r-- 1 mthreeof mthreeof 399M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads4.zip
-rw-r--r-- 1 mthreeof mthreeof 395M Dec 12 18:43 ./m3office.com/UpDraft_BackUp/backup_2016-12-12-1537_M3_Office_2a8328ca57c6-uploads11.zip
-rw-r--r-- 1 mthreeof mthreeof 7.3G Dec 20 08:34 ./m3office.com/html/wp-snapshots/20161205_m3office_58593079756c14578161220132201_archive.zip
-rw-r--r-- 1 mthreeof mthreeof 5.7G Dec  5 16:21 ./m3office.com/html/wp-snapshots/20161205_m3office_5845d87dd31cc1529161205211333_archive.zip

**Comment by CALLVES** [comment]
This is what they sent me: I have restarted the service and the site now appears to be loading again. There were many sleeping queries which were causing the max children limit to be reached. I have addressed these and the site now appears to load. Can you test the site on your end?

**Comment by CALLVES** [comment]
Hi Julia,

They sent me one more notice from the server support people:

Hello,

You still need to delete files because you are at 99% disk usage. Please free up some space within the next 72 hours so we can safely set your disk limit back to 30GB.

---------- Large Directories ---------------------------------------------------
121M    ./m3office.com/html.premove
16G     ./m3office.com/UpDraft_BackUp
8.1G    ./m3office.com/html/wp-content
5.8G    ./m3office.com/html/wp-snapshots
14G     ./m3office.com/html
30G     ./m3office.com
30G     .
-rw-r--r-- 1 mthreeof mthreeof 5.7G Dec  5 16:21 ./m3office.com/html/wp-snapshots/20161205_m3office_5845d87dd31cc1529161205211333_archive.zip

Regards,
Hassan

**Comment by juliafrichbeet** [comment]
Hello, Valerie! I finally get  a posiibility to find some wifi connection. I will delete all I can today, some of folders they mentioned are really important. But I guess I can upload latest backups on computer and delete old versions from server

**Comment by juliafrichbeet** [comment]
I will provide with update in few hours here

**Comment by juliafrichbeet** [comment]
Sorry, but I can not connect to the srver via FTP using credentials you nprovided before
Try this ftp: ftp: mthreeof.nextmp.net
u: M3dev@m3office.com
p: ViragoEpicSandalGnaws22

are they still valid? Thank you

**Comment by CALLVES** [comment]
Can you try this?

u: dev@callves.com
p: DuressCeasesSaberSering11

**Comment by CALLVES** [comment]
They sent me this note: Valerie,

It appears your current disk usage is at 30,021M. You need to be under 30,000M for your plan. It is highly recommended that you are at least 5,000M under your disk quota limit. Here is a breakdown of your disk usage:

[1842][root@obpsjc2-03 m3office.com]$ du -ch --max-depth 2 | sort -h
4.0K    ./html.premove/cgi-bin
4.0K    ./iworx-backup
100K    ./html.premove/jstemp
184K    ./html.premove/csstemp
1.7M    ./html.premove/imagestemp
6.4M    ./html/L
7.2M    ./html.premove/wp-admin
7.4M    ./html/wp-admin
7.5M    ./html/V
14M     ./html.premove/wp-includes
14M     ./html/wp-includes
55M     ./html/J
99M     ./html.premove/wp-content
121M    ./html.premove
5.8G    ./html/wp-snapshots
8.4G    ./html/wp-content
15G     ./html
16G     ./UpDraft_BackUp
30G     .
30G     total

**Comment by CALLVES** [comment]
Hi Julia, I noticed that when I went into the UpDraft backup plugin, there were 5 backup copies stored in the FTP. I changed it to only 3 so that should also reduce the file size. I hope. :D

**Comment by CALLVES** [comment]
Whenever you get done with all other items, please revisit this. The Nexcess support said that we still need to work on reducing the file sizes. So my thoughts are to stop the auto NEWS feed right now that are coming in from those 3 external sources.

**Comment by juliafrichbeet** [comment]
I cleared 10GB from live now! There have been some old backups from duplicator plugin, but the biggest folder is UpDraft_BackUp. Theere are lot of big folders backups there. I saved somw from 13/12 and removed them from live. But! As I understand server creates backups ones a week. So that is why it always not enough place . Anyway I will reduce uploads folder, too. So we'll see what will happen

**Comment by juliafrichbeet** [comment]
![image](https://cloud.githubusercontent.com/assets/24528105/21688829/ecc6f15a-d376-11e6-8c5a-b11b26ff8a7f.png)

**Comment by CALLVES** [comment]
You are awesome!

**Comment by juliafrichbeet** [comment]
Thank you! But I will still check it during next few weeks!
