### ISSUE TITLE
Social media links are not going to the correct links.

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#45]
The social media links from stay connected and contact page

**Comment by CALLVES** [comment]
Twitter: https://twitter.com/m3office
Instagram: https://www.instagram.com/theonlychair_/
Facebook: https://www.facebook.com/M3-Office-Inc-1761096594116418/
Pinterest: www.pinterest.com/m3offceinc

**Comment by juliafrichbeet** [comment]
I added a possibility to add links in admin panel! 
Please notice, for last icon you can add absolute or relative links

**Comment by CALLVES** [comment]
Thanks, I think we're good now. I'll close it.
