### ISSUE TITLE
PRODUCTS > SEATING page broke

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#46]
Hi Julia, please see the client's notes below: 

I attempted to change the image for the lounge chair button in the seating category and I appear have broken it somehow. Please see screenshot:

![screenshot 2017-01-03 18 00 38](https://cloud.githubusercontent.com/assets/20408671/21629586/a9b9414a-d1de-11e6-8c0e-afade7a8a9a1.jpg)

**Comment by CALLVES** [comment]
Just want you to know that I used the UpDraft backup and restore plugin in the WP admin. I restored to JAN 2, and now this page is fixed. BUT the issue at hand is why is it when the client tried to replace an image for the lounge chair it broke. Not sure how to answer this.

**Comment by CALLVES** [comment]
This is what client said:


I don’t know how I did it.  But I tried to do it again this morning and was able to do it no problem.  Our biggest issue that we need to work on (Alisa and I) is that we need to edit all of the images so that they view properly rather than being cut off.  I was also able to add a product.  There are a few tweaks that I saw last night.

1.       Under products/workspaces/systems furniture
Herman Miller Canvas is shown twice.  We need to remove the duplicate showing the private office image
 
2.       Under products/tables/training-dining
Eames table is shown twice. We need to remove the duplicate showing the eames dining.
3.       Why are there items under the workspaces section under product solutions?
4.       The search function doesn’t seem to be working.  I searched basic items like stool and table and nothing came up.
5.       When we edit the images to show properly on the buttons will they translate to the mobile version?  The buttons on the mobile version have a really small field for the image.  To much space is taken up by the title and the learn more button.  On all our sites the product image is a priority.    The title area and the button are limiting how much we see the actual image.
 
I will practice more today using the wordpress and hopefully I wont break it again.

**Comment by CALLVES** [comment]
So for no. 1 & 2 I believe you already fixed it.

For no. 3 I already addressed this with the client. What they mean is they see those WORKSPACES products under PRODUCT CATEGORIES but those same products should also be under PRODUCT SOLUTIONS > WORKSPACES. I told them they have to check the boxes in the PRODUCT EDIT view in WP admin so it's checked under WORKSPACES in PRODUCT SOLUTIONS as well. You can ignore.

For no. 4 I think she said now it works. You can ignore.

For no. 5 Let me know if you are done with this one so I can review it.

**Comment by juliafrichbeet** [comment]
Yep, I finished with first two items -  moved them to drafts,
#5 I showed you yesterday, I am ready to deploy it on live!
#4 really works

**Comment by CALLVES** [comment]
For no. 5 go ahead and deploy.

**Comment by juliafrichbeet** [comment]
Pushed to live!
Also I changed few categories images to check if templates work in appropriate way. Everything is Ok
