### ISSUE TITLE
Products page mobile view fix

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#47]
Hi Julia,

One more thing I just noticed, that on mobile view, using Chrome, I noticed there is a weird spacing issue with the 3 dropdown/search fields. It needs to be spaced evenly. Is this a big issue? See screenshot.
![unnamed](https://cloud.githubusercontent.com/assets/20408671/21651520/c0c1f2b8-d25d-11e6-9d26-203aa940b2f3.png)

**Comment by juliafrichbeet** [comment]
No, I will add all new styles changes tomorrow. what exactly space do you mean? under search field?

**Comment by CALLVES** [comment]
So if you look at the PRODUCT CATEGORIES dropdown then below that there is no space above the PRODUCT SOLUTIONS text. It needs to be spaced out nicely. That's what the client is seeing.

**Comment by juliafrichbeet** [comment]
I already fixed that on dev please let me know if I can move that to live! Thank you

**Comment by CALLVES** [comment]
Yes go ahead. Please. Thanks.

**Comment by juliafrichbeet** [comment]
Added all the fixes on live!
