### ISSUE TITLE
WP Admin shows DATABASE UPGRADE REQUIRED

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#48]
Julia, we'll need to take care of this upgrade on our end so the client doesn't keep asking if they should click on the blue button :(

**Comment by CALLVES** [comment]
And also noticed the WP version needs to be updated.

**Comment by juliafrichbeet** [comment]
For both of updates - I'll do it at night your time. it's something we have to be really carefull with

**Comment by CALLVES** [comment]
OK that sounds good.

**Comment by juliafrichbeet** [comment]
Updated. I changed some custom fileds values to check if everything is Ok, Anyway, I have latest DB backup

**Comment by CALLVES** [comment]
Thank you so much!!!
