### ISSUE TITLE
WP admin PRODUCTS backend > filter is not working

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#49]
When I go to the backend of PRODUCTS, there are 2 filter dropdowns that don't make sense:

SHOW ALL PRODUCT CATEGORIES
SHOW ALL CATEGORIES

Doesn't matter which one I select then I click on FILTER it doesn't do anything in the backend.

**Comment by juliafrichbeet** [comment]
I suppose we should leave select a category one - other do not work because of Wocommerce functionality

**Comment by CALLVES** [comment]
OK yeah just need 1 so it's not confusing. Let me know when you are done with this item

**Comment by juliafrichbeet** [comment]
I added new filter in admin panel both for dev and live. You can filter products by product sulotions and categories . please check the screenshot   -  
![image](https://cloud.githubusercontent.com/assets/24528105/21691975/71cf0c82-d383-11e6-8b75-62c518a883a1.png)

**Comment by CALLVES** [comment]
Thank you!
