### ISSUE TITLE
ipad Safari: STAY CONNECTED slide

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#5]
The button at the bottom is cutoff and you can only see the words partially. And the bottom of the background / image is also cutoff. See screenshot.
![2016-12-12 1](https://cloud.githubusercontent.com/assets/20408671/21110869/db87ede4-c053-11e6-923a-b875923fa553.png)

**Comment by juliafrichbeet** [comment]
Fixed, please check
