### ISSUE TITLE
Times New Roman is back

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#6]
Client sent in a screenshot showing that the Times New Roman is back. I'm not sure who uploaded and caused this...

See the URLs in the attached screenshot. We need to kill this once and for all that Times New Roman NEVER appears ever.
![10e09e6c16bd74e9f8bc5630f5bc23b9f9f9ec35f4e974aa42 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/20408671/21119159/20ed2328-c076-11e6-80b3-307142824395.png)

**Comment by CALLVES** [comment]
I just troubleshoot, this is happening on FF on PC and Mac. As well as on Safari on mobile.

**Comment by juliafrichbeet** [comment]
Sorry but it's lato-regular or lato-bold, please see the screenshot. Browsers render fonts in a different way, that is why fonts look different sometimes

**Comment by juliafrichbeet** [comment]
Also I checked if there is no 'Lato' or Times New Roman in project

**Comment by CALLVES** [comment]
Yeah apparently on FF on Mac it's still there, might be that issue again with the CSS. Remember what I sent you that the client sent me to use?

**Comment by juliafrichbeet** [comment]
Sorry, I don't. Does it appear on doggies page?

**Comment by CALLVES** [comment]
Yes it's on the DOGGIES page, just for the URL it seems. I see it on my PC FF as well...

**Comment by CALLVES** [comment]
Any updates on this Julia?

**Comment by juliafrichbeet** [comment]
Sorry, but I checked that before - it's Lato-bold. Please check the screenshot - 
![image](https://cloud.githubusercontent.com/assets/24528105/21405267/ddf7f854-c7cd-11e6-8e3c-57cfb543d438.png)
