### ISSUE TITLE
#001036 - PRODUCTS search & filter dropdowns on frontend and backend

### ISSUE THREAD

**Issue by CALLVES** [CALLVES/M3office#8]
FRONTEND: The search field, please also use capital letter P for Products.

BACKEND: There is a dropdown to filter products based on a category, we need one for the solutions. See screenshot:  https://www.dropbox.com/s/ez4o1v0dbnmjez2/screenshot-m3.callves.com-2016-11-29-13-09-58.png?dl=0"

**Comment by CALLVES** [comment]
FRONTEND: The Product Categories dropdown, capital "C" for Category.
Product Solutions dropdown, capital "S" or Solutions.

**Comment by juliafrichbeet** [comment]
Done for front end, get back to BE later

**Comment by CALLVES** [comment]
Confirmed FRONTEND is good.

**Comment by CALLVES** [comment]
Backend still needs to be worked on.

**Comment by juliafrichbeet** [comment]
I addded a possibility to filter products by all the parameters in admin DB, Please check on dev!

**Comment by CALLVES** [comment]
OK good this is good to deploy to live site. Thanks!
